https://www.kaggle.com/tunguz/atomic-distances-with-h2o-automl

In [4]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from sklearn.model_selection import GroupKFold

import os
print(os.listdir("../input"))

['sample_submission.csv', 'scalar_coupling_contributions.csv', 'structures', 'test.csv', 'structures.csv', 'dipole_moments.csv', 'mulliken_charges.csv', 'train.csv', 'magnetic_shielding_tensors.csv', 'potential_energy.csv']

In [5]:
train = pd.read_csv('../input/train.csv', index_col='id')
test = pd.read_csv('../input/test.csv', index_col='id')

/home/nagae/anaconda3/envs/gpu-env/lib/python3.6/site-packages/numpy/lib/arraysetops.py:569: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)

In [6]:
train.head()

,molecule_name,atom_index_0,atom_index_1,type,scalar_coupling_constant
id,,,,,
0,dsgdb9nsd_000001,1,0,1JHC,84.8076
1,dsgdb9nsd_000001,1,2,2JHH,-11.2570
2,dsgdb9nsd_000001,1,3,2JHH,-11.2548
3,dsgdb9nsd_000001,1,4,2JHH,-11.2543
4,dsgdb9nsd_000001,2,0,1JHC,84.8074

In [7]:
structures = pd.read_csv('../input/structures.csv')
display(structures.head())

      molecule_name  atom_index atom         x         y         z
0  dsgdb9nsd_000001           0    C -0.012698  1.085804  0.008001
1  dsgdb9nsd_000001           1    H  0.002150 -0.006031  0.001976
2  dsgdb9nsd_000001           2    H  1.011731  1.463751  0.000277
3  dsgdb9nsd_000001           3    H -0.540815  1.447527 -0.876644
4  dsgdb9nsd_000001           4    H -0.523814  1.437933  0.906397

In [8]:
def map_atom_info(df, atom_idx):
    df = pd.merge(df, structures, how = 'left',
                  left_on  = ['molecule_name', f'atom_index_{atom_idx}'],
                  right_on = ['molecule_name',  'atom_index'])
    
    df = df.drop('atom_index', axis=1)
    df = df.rename(columns={'atom': f'atom_{atom_idx}',
                            'x': f'x_{atom_idx}',
                            'y': f'y_{atom_idx}',
                            'z': f'z_{atom_idx}'})
    return df

train = map_atom_info(train, 0)
train = map_atom_info(train, 1)

test = map_atom_info(test, 0)
test = map_atom_info(test, 1)

In [9]:
train.head()

,molecule_name,atom_index_0,atom_index_1,type,scalar_coupling_constant,atom_0,x_0,y_0,z_0,atom_1,x_1,y_1,z_1
0,dsgdb9nsd_000001,1,0,1JHC,84.8076,H,0.002150,-0.006031,0.001976,C,-0.012698,1.085804,0.008001
1,dsgdb9nsd_000001,1,2,2JHH,-11.2570,H,0.002150,-0.006031,0.001976,H,1.011731,1.463751,0.000277
2,dsgdb9nsd_000001,1,3,2JHH,-11.2548,H,0.002150,-0.006031,0.001976,H,-0.540815,1.447527,-0.876644
3,dsgdb9nsd_000001,1,4,2JHH,-11.2543,H,0.002150,-0.006031,0.001976,H,-0.523814,1.437933,0.906397
4,dsgdb9nsd_000001,2,0,1JHC,84.8074,H,1.011731,1.463751,0.000277,C,-0.012698,1.085804,0.008001

In [10]:
%%time
# This block is SPPED UP

train_p_0 = train[['x_0', 'y_0', 'z_0']].values
train_p_1 = train[['x_1', 'y_1', 'z_1']].values
test_p_0 = test[['x_0', 'y_0', 'z_0']].values
test_p_1 = test[['x_1', 'y_1', 'z_1']].values

train['dist'] = np.linalg.norm(train_p_0 - train_p_1, axis=1)
test['dist'] = np.linalg.norm(test_p_0 - test_p_1, axis=1)

CPU times: user 492 ms, sys: 224 ms, total: 716 ms
Wall time: 218 ms

In [11]:
molecules = train.pop('molecule_name')
test = test.drop('molecule_name', axis=1)

In [12]:
train.head()

,atom_index_0,atom_index_1,type,scalar_coupling_constant,atom_0,x_0,y_0,z_0,atom_1,x_1,y_1,z_1,dist
0,1,0,1JHC,84.8076,H,0.002150,-0.006031,0.001976,C,-0.012698,1.085804,0.008001,1.091953
1,1,2,2JHH,-11.2570,H,0.002150,-0.006031,0.001976,H,1.011731,1.463751,0.000277,1.783120
2,1,3,2JHH,-11.2548,H,0.002150,-0.006031,0.001976,H,-0.540815,1.447527,-0.876644,1.783147
3,1,4,2JHH,-11.2543,H,0.002150,-0.006031,0.001976,H,-0.523814,1.437933,0.906397,1.783157
4,2,0,1JHC,84.8074,H,1.011731,1.463751,0.000277,C,-0.012698,1.085804,0.008001,1.091952

In [13]:
train['fold']=0

In [14]:
n_splits = 3
gkf = GroupKFold(n_splits=n_splits) # we're going to split folds by molecules


for fold, (in_index, oof_index) in enumerate(gkf.split(train, groups=molecules)):
    train.loc[oof_index, 'fold'] = fold

In [19]:
import h2o
print(h2o.__version__)
from h2o.automl import H2OAutoML

h2o.init()

3.18.0.2
Checking whether there is an H2O instance running at http://localhost:54321..... not found.
Attempting to start a local H2O server...
  Java Version: openjdk version "1.8.0_152-release"; OpenJDK Runtime Environment (build 1.8.0_152-release-1056-b12); OpenJDK 64-Bit Server VM (build 25.152-b12, mixed mode)
  Starting server from /home/nagae/anaconda3/envs/gpu-env/h2o_jar/h2o.jar
  Ice root: /tmp/tmp2i9ze4rm
  JVM stdout: /tmp/tmp2i9ze4rm/h2o_nagae_started_from_python.out
  JVM stderr: /tmp/tmp2i9ze4rm/h2o_nagae_started_from_python.err
  Server is running at http://127.0.0.1:54321
Connecting to H2O server at http://127.0.0.1:54321... successful.
Warning: Your H2O cluster version is too old (1 year, 5 months and 7 days)! Please download and install the latest version from http://h2o.ai/download/

--------------------------  ----------------------------------------
H2O cluster uptime:         01 secs
H2O cluster timezone:       Asia/Tokyo
H2O data parsing timezone:  UTC
H2O cluster version:        3.18.0.2
H2O cluster version age:    1 year, 5 months and 7 days !!!
H2O cluster name:           H2O_from_python_nagae_7ypy0p
H2O cluster total nodes:    1
H2O cluster free memory:    26.67 Gb
H2O cluster total cores:    8
H2O cluster allowed cores:  8
H2O cluster status:         accepting new members, healthy
H2O connection url:         http://127.0.0.1:54321
H2O connection proxy:
H2O internal security:      False
H2O API Extensions:         XGBoost, Algos, AutoML, Core V3, Core V4
Python version:             3.6.8 final
--------------------------  ----------------------------------------

In [20]:
train = h2o.H2OFrame(train)

/home/nagae/anaconda3/envs/gpu-env/lib/python3.6/site-packages/h2o/utils/shared_utils.py:170: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  data = _handle_python_lists(python_obj.as_matrix().tolist(), -1)[1]

Parse progress: |█████████████████████████████████████████████████████████| 100%

In [21]:
test = h2o.H2OFrame(test)

Parse progress: |█████████████████████████████████████████████████████████| 100%

In [22]:
train['type'] = train['type'].asfactor()
train['atom_0'] = train['atom_0'].asfactor()
train['atom_1'] = train['atom_1'].asfactor()

test['type'] = test['type'].asfactor()
test['atom_0'] = test['atom_0'].asfactor()
test['atom_1'] = test['atom_1'].asfactor()

In [23]:
x = test.columns
y = 'scalar_coupling_constant'

In [24]:
aml = H2OAutoML(max_models=2, seed=47, max_runtime_secs=3600)
aml.train(x=x, y=y, training_frame=train)

AutoML progress: |████████████████████████████████████████████████████████| 100%
Parse progress: |█████████████████████████████████████████████████████████| 100%

In [25]:
lb = aml.leaderboard
lb.head(rows=lb.nrows)

model_id,mean_residual_deviance,rmse,mae,rmsle
DRF_0_AutoML_20190812_214400,10.2566,3.2026,1.96633,nan
StackedEnsemble_BestOfFamily_0_AutoML_20190812_214400,10.4153,3.22727,1.99325,nan
StackedEnsemble_AllModels_0_AutoML_20190812_214400,10.4153,3.22727,1.99325,nan
XRT_0_AutoML_20190812_214400,10.7081,3.27233,2.03139,nan

In [26]:
aml.leader

Model Details
=============
H2ORandomForestEstimator :  Distributed Random Forest
Model Key:  DRF_0_AutoML_20190812_214400


ModelMetricsRegression: drf
** Reported on train data. **

MSE: 10.299018681750631
RMSE: 3.209208419805518
MAE: 1.9677778772489403
RMSLE: NaN
Mean Residual Deviance: 10.299018681750631

ModelMetricsRegression: drf
** Reported on validation data. **

MSE: 10.065618374733699
RMSE: 3.1726358717529655
MAE: 1.9485228638357468
RMSLE: NaN
Mean Residual Deviance: 10.065618374733699

ModelMetricsRegression: drf
** Reported on cross-validation data. **

MSE: 10.256647890535174
RMSE: 3.2026001765027075
MAE: 1.9663338594358073
RMSLE: NaN
Mean Residual Deviance: 10.256647890535174
Cross-Validation Metrics Summary:

                        mean     sd           cv_1_valid    cv_2_valid    cv_3_valid    cv_4_valid    cv_5_valid
----------------------  -------  -----------  ------------  ------------  ------------  ------------  ------------
mae                     1.96633  0.00266939   1.96497       1.97132       1.96389       1.96139       1.9701
mean_residual_deviance  10.2566  0.0480623    10.2096       10.3421       10.2074       10.1876       10.3365
mse                     10.2566  0.0480623    10.2096       10.3421       10.2074       10.1876       10.3365
r2                      0.9916   3.36442e-05  0.991617      0.991548      0.991615      0.991674      0.991548
residual_deviance       10.2566  0.0480623    10.2096       10.3421       10.2074       10.1876       10.3365
rmse                    3.20258  0.00749909   3.19525       3.21592       3.1949        3.1918        3.21505
rmsle                   0        nan          nan           nan           nan           nan           nan

Scoring History:

    timestamp            duration           number_of_trees    training_rmse    training_mae    training_deviance    validation_rmse    validation_mae    validation_deviance
--  -------------------  -----------------  -----------------  ---------------  --------------  -------------------  -----------------  ----------------  ---------------------
    2019-08-12 22:10:34  26 min 32.579 sec  0                  nan              nan             nan                  nan                nan               nan
    2019-08-12 22:10:39  26 min 37.530 sec  1                  3.78992          2.21971         14.3635              3.78528            2.21304           14.3283
    2019-08-12 22:10:44  26 min 42.461 sec  2                  3.73322          2.19915         13.937               3.50218            2.10845           12.2653
    2019-08-12 22:10:50  26 min 47.939 sec  3                  3.68721          2.16974         13.5955              3.39512            2.05653           11.5269
    2019-08-12 22:10:56  26 min 53.828 sec  4                  3.61788          2.13691         13.089               3.32946            2.02244           11.0853
    2019-08-12 22:11:04  27 min  1.866 sec  5                  3.56368          2.11419         12.6998              3.29562            2.00432           10.8611
    2019-08-12 22:11:15  27 min 12.927 sec  7                  3.48386          2.0772          12.1373              3.25828            1.98251           10.6164
    2019-08-12 22:11:26  27 min 23.837 sec  9                  3.41497          2.05226         11.662               3.23542            1.97392           10.4679
    2019-08-12 22:11:43  27 min 40.859 sec  12                 3.35246          2.02687         11.239               3.21805            1.96584           10.3558
    2019-08-12 22:12:00  27 min 57.950 sec  15                 3.31034          2.00821         10.9584              3.20199            1.95765           10.2528
    2019-08-12 22:12:21  28 min 19.555 sec  19                 3.27765          1.99835         10.743               3.19121            1.9574            10.1838
    2019-08-12 22:12:49  28 min 47.492 sec  24                 3.25173          1.98733         10.5738              3.18234            1.95365           10.1273
    2019-08-12 22:13:24  29 min 21.894 sec  30                 3.23248          1.97814         10.4489              3.17688            1.9503            10.0926
    2019-08-12 22:14:07  30 min  5.657 sec  38                 3.2211           1.97398         10.3755              3.1758             1.95061           10.0857
    2019-08-12 22:15:03  31 min  1.281 sec  48                 3.21237          1.96903         10.3193              3.17478            1.94925           10.0792
    2019-08-12 22:15:20  31 min 18.056 sec  50                 3.20921          1.96778         10.299               3.17264            1.94852           10.0656

Variable Importances:

variable      relative_importance    scaled_importance    percentage
------------  ---------------------  -------------------  ------------
dist          8.68322e+10            1                    0.486893
type          8.0922e+10             0.931935             0.453753
atom_index_1  3.61267e+09            0.0416051            0.0202573
atom_1        3.55015e+09            0.0408852            0.0199067
y_1           1.02267e+09            0.0117776            0.00573442
y_0           8.48011e+08            0.00976609           0.00475504
atom_index_0  6.95163e+08            0.00800582           0.00389798
x_0           3.01652e+08            0.00347397           0.00169145
z_0           2.37516e+08            0.00273534           0.00133182
x_1           1.83996e+08            0.00211898           0.00103172
z_1           1.33305e+08            0.0015352            0.000747479

In [27]:
preds = aml.predict(test)
sample_submission = pd.read_csv('../input/sample_submission.csv')
sample_submission['scalar_coupling_constant'] = preds.as_data_frame().values.flatten()
sample_submission.to_csv('h2o_submission_3.csv', index=False)

Parse progress: |█████████████████████████████████████████████████████████| 100%
drf prediction progress: |████████████████████████████████████████████████| 100%